
package tr.gov.udhb.unetws.uetds;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UdhbUetdsAriziService", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", wsdlLocation = "https://servis.turkiye.gov.tr/services/g2g/kdgm/test/uetdsarizi?wsdl")
public class UdhbUetdsAriziService_Service
    extends Service
{

    private final static URL UDHBUETDSARIZISERVICE_WSDL_LOCATION;
    private final static WebServiceException UDHBUETDSARIZISERVICE_EXCEPTION;
    private final static QName UDHBUETDSARIZISERVICE_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "UdhbUetdsAriziService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://servis.turkiye.gov.tr/services/g2g/kdgm/test/uetdsarizi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UDHBUETDSARIZISERVICE_WSDL_LOCATION = url;
        UDHBUETDSARIZISERVICE_EXCEPTION = e;
    }

    public UdhbUetdsAriziService_Service() {
        super(__getWsdlLocation(), UDHBUETDSARIZISERVICE_QNAME);
    }

    public UdhbUetdsAriziService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UDHBUETDSARIZISERVICE_QNAME, features);
    }

    public UdhbUetdsAriziService_Service(URL wsdlLocation) {
        super(wsdlLocation, UDHBUETDSARIZISERVICE_QNAME);
    }

    public UdhbUetdsAriziService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UDHBUETDSARIZISERVICE_QNAME, features);
    }

    public UdhbUetdsAriziService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UdhbUetdsAriziService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UdhbUetdsAriziService
     */
    @WebEndpoint(name = "UdhbUetdsAriziServicePort")
    public UdhbUetdsAriziService getUdhbUetdsAriziServicePort() {
        return super.getPort(new QName("http://uetds.unetws.udhb.gov.tr/", "UdhbUetdsAriziServicePort"), UdhbUetdsAriziService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UdhbUetdsAriziService
     */
    @WebEndpoint(name = "UdhbUetdsAriziServicePort")
    public UdhbUetdsAriziService getUdhbUetdsAriziServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uetds.unetws.udhb.gov.tr/", "UdhbUetdsAriziServicePort"), UdhbUetdsAriziService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UDHBUETDSARIZISERVICE_EXCEPTION!= null) {
            throw UDHBUETDSARIZISERVICE_EXCEPTION;
        }
        return UDHBUETDSARIZISERVICE_WSDL_LOCATION;
    }

}
