
package tr.gov.udhb.unetws.uetds;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UdhbUetdsAriziService", targetNamespace = "http://uetds.unetws.udhb.gov.tr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UdhbUetdsAriziService {


    /**
     * 
     * @param seferYolcuRefNo
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsYolcuBildirimSorguSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuBildirimSorgula")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "yolcuBildirimSorgula", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuBildirimSorgula")
    @ResponseWrapper(localName = "yolcuBildirimSorgulaResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuBildirimSorgulaResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuBildirimSorgula", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/yolcuBildirimSorgulaResponse")
    public UetdsYolcuBildirimSorguSonuc yolcuBildirimSorgula(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "seferYolcuRefNo", targetNamespace = "")
        String seferYolcuRefNo);

    /**
     * 
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @param gelmeyenYolcu
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuGelmeyenBildir")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "yolcuGelmeyenBildir", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuGelmeyenBildir")
    @ResponseWrapper(localName = "yolcuGelmeyenBildirResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuGelmeyenBildirResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuGelmeyenBildir", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/yolcuGelmeyenBildirResponse")
    public UetdsGenelIslemSonuc yolcuGelmeyenBildir(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "gelmeyenYolcu", targetNamespace = "")
        UetdsAriziYolcuGelmeyenInput gelmeyenYolcu);

    /**
     * 
     * @param testMsj1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/servisTest")
    @WebResult(name = "servisTestResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", partName = "servisTestResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/servisTest", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/servisTestResponse")
    public String servisTest(
        @WebParam(name = "testMsj1", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", partName = "testMsj1")
        String testMsj1);

    /**
     * 
     * @param bagajBilgileri
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuBagajIptal")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "yolcuBagajIptal", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuBagajIptal")
    @ResponseWrapper(localName = "yolcuBagajIptalResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuBagajIptalResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuBagajIptal", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/yolcuBagajIptalResponse")
    public UetdsGenelIslemSonuc yolcuBagajIptal(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "bagajBilgileri", targetNamespace = "")
        UetdsSeferBagajBilgileriInput bagajBilgileri);

    /**
     * 
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @param tasitPlakaNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferPlakaDegistir")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seferPlakaDegistir", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferPlakaDegistir")
    @ResponseWrapper(localName = "seferPlakaDegistirResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferPlakaDegistirResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferPlakaDegistir", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/seferPlakaDegistirResponse")
    public UetdsGenelIslemSonuc seferPlakaDegistir(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "tasitPlakaNo", targetNamespace = "")
        String tasitPlakaNo);

    /**
     * 
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsSeferBildirimOzetSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/bildirimOzeti")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bildirimOzeti", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.BildirimOzeti")
    @ResponseWrapper(localName = "bildirimOzetiResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.BildirimOzetiResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/bildirimOzeti", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/bildirimOzetiResponse")
    public UetdsSeferBildirimOzetSonuc bildirimOzeti(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo);

    /**
     * 
     * @param iptalAciklama
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferIptal")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seferIptal", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferIptal")
    @ResponseWrapper(localName = "seferIptalResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferIptalResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferIptal", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/seferIptalResponse")
    public UetdsGenelIslemSonuc seferIptal(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "iptalAciklama", targetNamespace = "")
        String iptalAciklama);

    /**
     * 
     * @param aktifAciklama
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferAktif")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seferAktif", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferAktif")
    @ResponseWrapper(localName = "seferAktifResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferAktifResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferAktif", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/seferAktifResponse")
    public UetdsGenelIslemSonuc seferAktif(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "aktifAciklama", targetNamespace = "")
        String aktifAciklama);

    /**
     * 
     * @param ariziSeferBilgileriInput
     * @param wsuser
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsAriziSeferBildirSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferEkle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seferEkle", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferEkle")
    @ResponseWrapper(localName = "seferEkleResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferEkleResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferEkle", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/seferEkleResponse")
    public UetdsAriziSeferBildirSonuc seferEkle(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "ariziSeferBilgileriInput", targetNamespace = "")
        UetdsAriziSeferBilgileriInput ariziSeferBilgileriInput);

    /**
     * 
     * @param seferPersonelBilgileriInput
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/personelEkle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "personelEkle", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.PersonelEkle")
    @ResponseWrapper(localName = "personelEkleResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.PersonelEkleResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/personelEkle", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/personelEkleResponse")
    public UetdsGenelIslemSonuc personelEkle(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        long uetdsSeferReferansNo,
        @WebParam(name = "seferPersonelBilgileriInput", targetNamespace = "")
        List<UetdsAriziSeferPersonelBilgileriInput> seferPersonelBilgileriInput);

    /**
     * 
     * @param bagajBilgileri
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuBagajEkle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "yolcuBagajEkle", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuBagajEkle")
    @ResponseWrapper(localName = "yolcuBagajEkleResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuBagajEkleResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuBagajEkle", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/yolcuBagajEkleResponse")
    public UetdsGenelIslemSonuc yolcuBagajEkle(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "bagajBilgileri", targetNamespace = "")
        List<UetdsSeferBagajBilgileriInput> bagajBilgileri);

    /**
     * 
     * @param wsuser
     * @param iptalPersonelInput
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/personelIptal")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "personelIptal", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.PersonelIptal")
    @ResponseWrapper(localName = "personelIptalResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.PersonelIptalResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/personelIptal", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/personelIptalResponse")
    public UetdsGenelIslemSonuc personelIptal(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "iptalPersonelInput", targetNamespace = "")
        UetdsPersonelIptalInput iptalPersonelInput);

    /**
     * 
     * @param seferYolcuBilgileriInput
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsAriziYolcuIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuEkle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "yolcuEkle", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuEkle")
    @ResponseWrapper(localName = "yolcuEkleResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuEkleResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuEkle", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/yolcuEkleResponse")
    public UetdsAriziYolcuIslemSonuc yolcuEkle(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "seferYolcuBilgileriInput", targetNamespace = "")
        UetdsAriziSeferYolcuBilgileriInput seferYolcuBilgileriInput);

    /**
     * 
     * @param iptalYolcu
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuIptal")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "yolcuIptal", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuIptal")
    @ResponseWrapper(localName = "yolcuIptalResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuIptalResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuIptal", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/yolcuIptalResponse")
    public UetdsGenelIslemSonuc yolcuIptal(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "iptalYolcu", targetNamespace = "")
        UetdsAriziYolcuIptalInput iptalYolcu);

    /**
     * 
     * @param iptalAciklama
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @param uetdsYolcuReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsGenelIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuIptalUetdsYolcuRefNoIle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "yolcuIptalUetdsYolcuRefNoIle", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuIptalUetdsYolcuRefNoIle")
    @ResponseWrapper(localName = "yolcuIptalUetdsYolcuRefNoIleResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.YolcuIptalUetdsYolcuRefNoIleResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/yolcuIptalUetdsYolcuRefNoIle", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/yolcuIptalUetdsYolcuRefNoIleResponse")
    public UetdsGenelIslemSonuc yolcuIptalUetdsYolcuRefNoIle(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "uetdsYolcuReferansNo", targetNamespace = "")
        Long uetdsYolcuReferansNo,
        @WebParam(name = "iptalAciklama", targetNamespace = "")
        String iptalAciklama);

    /**
     * 
     * @param guncellenecekSeferReferansNo
     * @param ariziSeferBilgileriInput
     * @param wsuser
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsTarifeliSeferBildirSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferGuncelle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seferGuncelle", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferGuncelle")
    @ResponseWrapper(localName = "seferGuncelleResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferGuncelleResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferGuncelle", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/seferGuncelleResponse")
    public UetdsTarifeliSeferBildirSonuc seferGuncelle(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "guncellenecekSeferReferansNo", targetNamespace = "")
        Long guncellenecekSeferReferansNo,
        @WebParam(name = "ariziSeferBilgileriInput", targetNamespace = "")
        UetdsAriziSeferBilgileriInput ariziSeferBilgileriInput);

    /**
     * 
     * @param seferGrupBilgileriInput
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsAriziGrupIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferGrupEkle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seferGrupEkle", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferGrupEkle")
    @ResponseWrapper(localName = "seferGrupEkleResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferGrupEkleResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferGrupEkle", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/seferGrupEkleResponse")
    public UetdsAriziGrupIslemSonuc seferGrupEkle(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "seferGrupBilgileriInput", targetNamespace = "")
        UetdsAriziGrupBilgileriInput seferGrupBilgileriInput);

    /**
     * 
     * @param seferGrupBilgileriInput
     * @param grupId
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsAriziGrupIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferGrupGuncelle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seferGrupGuncelle", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferGrupGuncelle")
    @ResponseWrapper(localName = "seferGrupGuncelleResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferGrupGuncelleResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferGrupGuncelle", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/seferGrupGuncelleResponse")
    public UetdsAriziGrupIslemSonuc seferGrupGuncelle(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo,
        @WebParam(name = "grupId", targetNamespace = "")
        Long grupId,
        @WebParam(name = "seferGrupBilgileriInput", targetNamespace = "")
        UetdsAriziGrupBilgileriInput seferGrupBilgileriInput);

    /**
     * 
     * @param wsuser
     * @param uetdsSeferReferansNo
     * @return
     *     returns tr.gov.udhb.unetws.uetds.UetdsAriziGrupIslemSonuc
     */
    @WebMethod(action = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferGrupListesi")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seferGrupListesi", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferGrupListesi")
    @ResponseWrapper(localName = "seferGrupListesiResponse", targetNamespace = "http://uetds.unetws.udhb.gov.tr/", className = "tr.gov.udhb.unetws.uetds.SeferGrupListesiResponse")
    @Action(input = "http://uetds.unetws.udhb.gov.tr/uetdsytsarizi/seferGrupListesi", output = "http://uetds.unetws.udhb.gov.tr/UdhbUetdsAriziService/seferGrupListesiResponse")
    public UetdsAriziGrupIslemSonuc seferGrupListesi(
        @WebParam(name = "wsuser", targetNamespace = "")
        UetdsYtsUser wsuser,
        @WebParam(name = "uetdsSeferReferansNo", targetNamespace = "")
        Long uetdsSeferReferansNo);

}
